### ISSUE TITLE
Documentation needed

### ISSUE THREAD

**Issue by JijoBose** [Kida007/react-native-scratcher#2]
Please update the list of properties need to be sent to the component

**Comment by Kida007** [comment]
Hey @JijoBose 

Thanks for your interest in the library. Currently this package is in making and not functional on IOS because of one of its dependency.

I have made a PR to that dependency, once it gets merged i will launch the package with documentation.

Although there is a workaround for this IOS problem . I will post the Component usage and the IOS workaround soon.

**Comment by JijoBose** [comment]
I'm currently implementing this in Android, 
If your IOS package would take time, it's totally fine.

But It would be helpful if you could include an example implementation of the scratch card with required props

**Comment by Kida007** [comment]
Here is an example : 

```
import ScratchView from "react-native-scratch-view";
```
usage: 
```
<ScratchView
            style={{ height: 300, width: 300 }}
            scratchImage={require("./assets/pin.jpg")}
            onRevealed={this.onScratched}
            spotRadius={13}
            autoRevealPercentage={0.9}
          >
            <View
              style={{
                flex: 1,
                justifyContent: "center",
                alignItems: "center"
              }}
            >
              <Text>Your Hidden Prize</Text>
            </View>
</ScratchView>
```
